### ISSUE TITLE
Possibility of a Starforged version?

### ISSUE THREAD

**Issue by themaster567** [thexhr/isscrolls#9]
Just curious, I'm only familiar with that version of the game. That said, I do intend to play Ironsworn as well, so this will still be very fun!

**Comment by thexhr** [comment]
Hi @themaster567 ,

currently, I have no plans to develop a Starforged based version. Although I own the material, I don't play the game myself. Maybe that's an opportunity to try to get into the game :)

I'll leave this issue here open and labelled as enhancement, however, I cannot promise anything.

Cheers

**Comment by thexhr** [comment]
Quick update. I still don't play SF, however, Starforged Sundered Isles is out since some days. I already committed some early alpha, still undocumented, code to support SI. Feel free to check out latest git code and give it a try.

**Comment by thexhr** [comment]
Next update. I realized that SI actually uses the Starforged rules, so yes, support will be done in the next weeks.

**Comment by thexhr** [comment]
2024.a is now live with code and documentation support for SF. Have fun!

**Comment by themaster567** [comment]
Sorry for the late respond but thank you for this!
